version: '3.0'
services:
  grafana:
    container_name: 'blackcowmoo-google-analytics-datasource'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
        PLUGINS_NAME: "blackcowmoo-googleanalytics-datasource"
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/blackcowmoo-google-analytics-datasource
      - ./provisioning:/etc/grafana/provisioning
