name: github-actions/backend/lint
on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.2'

      - run: go get -u -d github.com/magefile/mage
      - name: Build
        run: |
          go get -d -v
          go build -v .

      - run: mage lint
