name: github-actions/backend/test
on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.15.2"

      - name: Build
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: buildAll

      - name: Test
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: test

      # TODO: Coverage
      # - name: Coverage
      #   uses: magefile/mage-action@v1
      #   with:
      #     version: latest
      #     args: coverage
